server:
  port: 8090

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]': # wildcard for all paths
            allowedOrigins:
              - "http://localhost:8080" # Changed localhost to this to fix the problem with CORS
            allowedMethods:
              - "*"
            allowCredentials: true
            allowedHeaders:
              - "*" # Changed localhost to this to fix the problem with CORS

      discovery:
        locator:
          enabled:true
      routes:
        -   id: log-service
            uri: lb://log-service
            predicates:
              - Path=/log/**
            filters:
              - RewritePath=/log/(?<path>.*), /$\{path}
        -   id: product-service
            uri: lb://product-service
            predicates:
              - Path=/product/**
            filters:
              - RewritePath=/product/(?<path>.*), /$\{path}
        -   id: shop-service
            uri: lb://shop-service
            predicates:
              - Path=/shop/**
            filters:
              - RewritePath=/shop/(?<path>.*), /$\{path}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka
